<?php

/**
 * @file
 * Model platform - Dashboard
 */

define('MP_DASHBOARD_CUSTOMER_ACCESS', 'customer dashboard access');
define('MP_DASHBOARD_ACCESS', 'modelplatform dashboard access');

define('MP_DASHBOARD_MODEL_MY_JOBS_ACCESS', 'my jobs page access');

/**
 * Implements hook_menu().
 */
function mp_dashboard_menu() {
  $items = array();

  $items['customer/dashboard'] = array(
    'title' => t('Dashboard'),
    'page callback' => 'mp_dashboard_clear_page',
    'access arguments' => array(MP_DASHBOARD_CUSTOMER_ACCESS),
  );
  $items['dashboard'] = array(
    'title' => t('Dashboard'),
    'page callback' => 'mp_dashboard_clear_page',
    'access arguments' => array(MP_DASHBOARD_CUSTOMER_ACCESS),
  );
  $items['user/%/edit/my_jobs'] = array(
    'title' => t('My Jobs'),
    'page callback' => 'mp_dashboard_clear_page',
    'access arguments' => array(MP_DASHBOARD_MODEL_MY_JOBS_ACCESS),
  );

  return $items;
}

/**
 * Generate clear page.
 */
function mp_dashboard_clear_page() {
  return '';
}

/**
 * Implements hook_permission().
 */
function mp_dashboard_permission() {
  return array(
    MP_DASHBOARD_CUSTOMER_ACCESS => array(
      'title' => t('Customer dashboard access'),
      'description' => t('Perform customer dashboard access.'),
    ),
    MP_DASHBOARD_ACCESS => array(
      'title' => t('Dashboard access'),
      'description' => t('Perform dashboard access.'),
    ),
    MP_DASHBOARD_MODEL_MY_JOBS_ACCESS => array(
      'title' => t('My jobs page access'),
      'description' => t('Perform access to the my jobs page.'),
    ),
  );
}

/**
 * Implements hook_quicktabs_alter().
 */
function mp_dashboard_quicktabs_alter(&$quicktabs) {
  if (isset($quicktabs->tabs)) {
    $tabs = $quicktabs->tabs;
    foreach ($tabs as $key => $tab) {
      $quicktabs->tabs[$key]['title'] = t($tab['title']);
    }
  }
}
