<?php

/**
 * @file
 */


/**
 * Implements hook_votingapi_insert().
 */
function mp_rating_votingapi_insert($votes) {
  foreach($votes as $vote) {
    if ($vote['entity_type'] == 'bat_event') {
      $event_id = $vote['entity_id'];
      $event = bat_event_load($event_id);
      $event_wrapper = entity_metadata_wrapper('bat_event', $event);
      $unit = $event_wrapper->event_bat_unit_reference->value();
      $job = $event_wrapper->field_job->value();
      $model_uid = $unit->uid;
      $customer_uid = $job->uid;

      _votingapi_prep_vote($vote);
      $vote['entity_type'] = 'user';
      unset($vote['vote_id']);
      if ($vote['uid'] == $model_uid) {
        $vote['entity_id'] = $customer_uid;
      }
      elseif ($vote['uid'] == $customer_uid) {
        $vote['entity_id'] = $model_uid;
      }
      _fivestar_update_field_value($vote['entity_type'], user_load($vote['entity_id']), 'field_rating', LANGUAGE_NONE, $vote['value']);
      _mp_rating_remove_row($vote['uid'], $event_id);
    }
  }
}

/**
 * Block callback;
 */
function _modelplatform_job_rate_block() {
  global $user;

  $display_id = 'block';
  if (_modelplatform_user_is_model($user)) {
    $display_id = 'block';
  }
  if (_modelplatform_user_is_customer($user)) {
    $display_id = 'block_1';
  }
  $event_data = _mp_rating_get_user_rate_events($user->uid);

  $content = array();
  foreach($event_data as $event_info) {
    $content[] = '<div class="rating-row">'
      . views_embed_view('rate_job_event', $display_id, $event_info->job_nid)
      . '</div>';
  }

  return count($content) ? array('subject' => '', 'content' => implode('', $content)) : array();
}



/**
 * Implements hook_modelplatform_job_complete().
 */
function mp_rating_modelplatform_job_complete($job_nid, $event_id) {
  $job = node_load($job_nid);
  $event = bat_event_load($event_id);
  $event_wrapper = entity_metadata_wrapper('bat_event', $event);
  $unit = $event_wrapper->event_bat_unit_reference->value();

  $model_item = array(
    'uid' => $unit->uid,
    'event_id' => $event_id,
    'job_nid' => $job->nid,
  );
  _mp_rating_fill_row($model_item);

  $customer_item = array(
    'uid' => $job->uid,
    'event_id' => $event_id,
    'job_nid' => $job->nid,
  );
  _mp_rating_fill_row($customer_item);
}

/**
 * Implements hook_block_info().
 */
function modelplatform_block_info() {
  $blocks = array();

  $blocks['mp_rating_block'] = array(
    'info' => t('Job - Rating'),
    'cache' => DRUPAL_NO_CACHE,
    'region ' => 'content',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function modelplatform_block_view($delta = '') {
  switch ($delta) {
    case 'mp_rating_block':
      $block = _modelplatform_job_rate_block();
      break;

    default:
      $block = array();
  }

  return $block;
}
