<?php

/**
 * @file
 * Xing Module for Drupal Sites.
 */

/**
 * Implements hook_help().
 */
function login_with_xing_help($path, $arg) {
  switch ($path) {
    case 'admin/help#login_with_xing':
      return '<p>' . t('User can click on the "Login with Xing" button on the user login page and able to login to system as well as "Register with Xing" button on registration page.') . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function login_with_xing_permission() {
  return array(
    'administer xing' => array(
      'title' => t('Administer xing'),
      'description' => t('Administer Xing Connect Module settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function login_with_xing_menu() {
  $items = array();

  $items['admin/config/people/login_with_xing'] = array(
    'title' => 'Login with Xing     api key Settings',
    'description' => 'Configuration of Xing features',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('login_with_xing_admin_api_key_setting'),
    'access arguments' => array('administer xing'),
    'file' => 'form/login_with_xing.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['login_with_xing/save'] = array(
    'title' => 'Authentication of xing',
    'description' => 'Handle the authentication of xing.',
    'page callback' => 'login_with_xing_process_save',
    'file' => 'includes/login_with_xing.process.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function login_with_xing_theme() {
  return array(
    'login_with_xing_button_display' => array(
      'variables' => array('data' => NULL),
      'template' => 'templates/login_with_xing',
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function login_with_xing_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      // Checking wheather consumer and secreat key set to show login with xing
      // link.
      if (variable_get('login_with_xing_ckey')) {

        $variables = array(
          'path' => 'login_with_xing/save',
          'query' => drupal_get_query_parameters(),
        );

        $form['xing_btn'] = array(
          '#type' => 'markup',
          '#theme' => 'login_with_xing_button_display',
          '#data' => $variables,
          '#weight' => -10,
        );
      }
      else {
        watchdog('login_with_xing', 'Xing API keys is not configured correctly.');
        drupal_set_message(t('Xing API keys/secreat key is not configured correctly.'), 'warning');
      }
      break;
  }
}

/**
 * Redirect an external request.
 *
 * There is an issue with securepages and drupal_goto which
 * overides https requests if they are not in its list of pages
 * which also can only be internal pages. There is some
 * discussion on this issue here;
 *
 * @see https://drupal.org/node/2022229
 */
function login_with_xing_external_goto($path, $options) {
  $url = url($path, $options);
  header('Location: ' . $url, TRUE, '302');
  drupal_exit();
}

/**
 * Generates a unique username for drupal site based on XING username.
 */
function login_with_xing_unique_user_name($xing_name, $i = 0) {
  $trimmed_name = '';
  $user_to_load = '';
  if ($i == 0) {
    $trimmed_name = strtolower(trim(str_replace(' ', '_', $xing_name)));
    $user_to_load = $trimmed_name;
  }
  else {
    $trimmed_name = $xing_name;
    $user_to_load = $trimmed_name . "_" . $i;
  }

  // Check if user exists by loading userbyname.
  if (is_object(user_load_by_name($user_to_load))) {
    $i++;
    return (login_with_xing_unique_user_name($trimmed_name, $i));
  }
  else {
    return $user_to_load;
  }
}
