<?php

/**
 * @file
 * Model platform - PDF module.
 */

define('MP_PDF_BLOCK_POLICY', 17);
define('MP_PDF_BLOCK_TERMS', 18);
define('MP_PDF_NODE_IMPRINT', 236);

/**
 * Implements hook_menu().
 */
function mp_pdf_menu() {
  $items = array();

  $items['mp_pdf/terms'] = array(
    'title' => t('Privace policy and Terms'),
    'page callback' => 'mp_pdf_policy_terms',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['mp_pdf/imprint'] = array(
    'title' => t('Imprint'),
    'page callback' => 'mp_pdf_imprint',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_node_view_alter().
 */
function mp_pdf_node_view_alter(&$build) {
  $node = $build['#node'];

  switch($node->nid) {
    case 216:
      $link = 'mp_pdf/terms';
      break;

    case 236:
      $link = 'mp_pdf/imprint';
      break;

    default:
      $link = '';
  }

  if ($link) {
    $build['mp_pdf_link'] = array(
      '#type' => 'markup',
      '#markup' => l(t('Print'), $link, array('attributes' => array('class' => array('mp-pdf-link')))),
      '#weight' => -1,
    );
  }
}

function mp_pdf_policy_terms() {
  $block = module_invoke('block', 'block_view', MP_PDF_BLOCK_POLICY);
  $policy = render($block['content']);

  $block = module_invoke('block', 'block_view', MP_PDF_BLOCK_TERMS);
  $terms = render($block['content']);

  $html = $policy . $terms;

  pdf_using_mpdf_api($html);
}

function mp_pdf_imprint() {
  $node = node_load(MP_PDF_NODE_IMPRINT);
  $node_view = node_view($node, 'full');
  $imprint = render($node_view);

  pdf_using_mpdf_api($imprint);
}