<?php

/**
 * @file
 * Model Platform - MangoPay module.
 */

// Helper functions.
require_once 'mp_mangopay.inc';

// API functions.
require_once 'includes/mp_mangopay.api.inc';

// DB helper functions.
require_once 'includes/db/mp_mangopay.db.inc';

define('MP_MANGOPAY_CONFIG_FORM_ACCESS', 'manage mangopay');

/**
 * Implements hook_menu().
 */
function mp_mangopay_menu() {
  $items = array();

  $module_path = drupal_get_path('module', 'mp_mangopay');

  $items['admin/config/magopay'] = array(
    'title' => 'MangoPay',
    'description' => 'MangoPay specific settings.',
    'access arguments' => array(MP_MANGOPAY_CONFIG_FORM_ACCESS),
  );
  $items['admin/config/magopay/settings'] = array(
    'title' => 'MangoPay Settings',
    'description' => 'Configure settings for MangoPay API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_mangopay_config_form'),
    'access arguments' => array(MP_MANGOPAY_CONFIG_FORM_ACCESS),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mp_mangopay.config_form.inc',
    'file path' => $module_path . '/includes/forms',
  );
  $items['user/%user/invoices/%commerce_order/payment'] = array(
    'title' => 'Payment',
    'description' => 'Invoice payment.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_mangopay_payment_form', 1, 3),
    'access callback' => 'mp_invoices_access_own_invoices',
    'access arguments' =>  array(1, 3),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mp_mangopay.payment_form.inc',
    'file path' => $module_path . '/includes/forms',
  );

  $items['user/%user/invoices/%commerce_order/payment_result'] = array(
    'title' => 'Payment result',
    'description' => 'Invoice payment result.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_mangopay_payment_callback_form', 1, 3),
    'access callback' => 'mp_invoices_access_own_invoices',
    'access arguments' =>  array(1, 3),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mp_mangopay.payment_form.inc',
    'file path' => $module_path . '/includes/forms',
  );

  t('Payment');
  t('MangoPay');
  t('MangoPay Settings');

  return $items;
}

/**
 * Implements hook_permission().
 */
function mp_mangopay_permission() {
  $permissions = array(
    MP_MANGOPAY_CONFIG_FORM_ACCESS => array(
      'title' => t('Administer mangopay'),
      'description' => t('Can configure mangopay parameters.'),
    ),
  );

  return $permissions;
}
