<?php

/**
 * @file
 * Model Platform - MangoPay module.
 */

// Helper functions.
require_once 'mp_mangopay.inc';

// API functions.
require_once 'includes/mp_mangopay.api.inc';

// DB helper functions.
require_once 'includes/db/mp_mangopay.db.inc';

define('MP_MANGOPAY_CONFIG_FORM_ACCESS', 'manage mangopay');

/**
 * Implements hook_menu().
 */
function mp_mangopay_menu() {
  $items = array();

  $module_path = drupal_get_path('module', 'mp_mangopay');

  $items['admin/config/mangopay'] = array(
    'title' => 'MangoPay',
    'description' => 'MangoPay specific settings.',
    'access arguments' => array(MP_MANGOPAY_CONFIG_FORM_ACCESS),
  );
  $items['admin/config/mangopay/settings'] = array(
    'title' => 'MangoPay Settings',
    'description' => 'Configure settings for MangoPay API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_mangopay_config_form'),
    'access arguments' => array(MP_MANGOPAY_CONFIG_FORM_ACCESS),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mp_mangopay.config_form.inc',
    'file path' => $module_path . '/includes/forms',
  );

  $items['user/%user/invoices/%commerce_order/payment'] = array(
    'title' => 'Payment result',
    'description' => 'Invoice payment result.',
    'page callback' => 'mp_mangopay_payment_callback_form',
    'page arguments' => array(NULL, 3),
    'access callback' => 'mp_invoices_access_own_invoices',
    'access arguments' =>  array(NULL, 3),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mp_mangopay.payment_form.inc',
    'file path' => $module_path . '/includes/forms',
  );

  $items['mangopay/ajax/%commerce_order/%'] = array(
    'page callback' => 'mp_mangopay_card_request',
    'access callback' => 'mp_invoices_access_own_invoices',
    'access arguments' =>  array(NULL, 2),
    'type' => MENU_NORMAL_ITEM,
  );

  t('Payment');
  t('MangoPay');
  t('MangoPay Settings');

  return $items;
}

/**
 * Implements hook_permission().
 */
function mp_mangopay_permission() {
  $permissions = array(
    MP_MANGOPAY_CONFIG_FORM_ACCESS => array(
      'title' => t('Administer mangopay'),
      'description' => t('Can configure mangopay parameters.'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_block_info().
 */
function mp_mangopay_block_info() {
  $blocks = array();
  $blocks['mp_mangopay_payment_form'] = array(
    'info' => t('Payment form'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mp_mangopay_block_view($delta = '') {
  switch ($delta) {
    case 'mp_mangopay_payment_form':
      require_once 'includes/forms/mp_mangopay.payment_form.inc';
      $args = arg();
      $block = array();
      if (!isset($args[4])) {
        $block['subject'] = '';
        $block['content'] = mp_mangopay_payment_form(user_load($args[1]), commerce_order_load($args[3]));
      }
      break;

    default:
      $block = array();
  }

  return $block;
}