<?php

/**
 * Created by PhpStorm.
 * User: cimpleo
 * Date: 21.12.16
 * Time: 13:29
 */

/**
 * Implements hook_form_alter().
 */
function mp_registration_form_alter(&$form, &$form_state, $form_id) {
  // Switch if in the feature we will need alter more then 1 registration form.
  switch ($form_id) {
    case 'user_register_form':
      $selector = 'input[name="user_roles"]';
      $form['field_small_business']['#states'] = array(
        'visible' => array(
          array(
            $selector => array(
              'value' => 5,
            ),
          ),
        ),
        'invisible' => array(
          array(
            $selector => array(
              '!value' => 5,
            ),
          ),
        ),
      );
      $form['autoassignrole_user']['#weight'] = -100;
      break;

    default:
      // Nothing to do.
  }
}

/**
 * Implements hook_xing_connect_register_alter().
 */
function mp_registration_xing_connect_register_alter(&$fields, $xing_candidate_info) {
  $fields['roles'][4] = 'Customer';
}
