<?php

/**
 * @file
 * Model Platform - Galleries module.
 */

/**
 * Implements hook_user_insert().
 */
function mp_galleries_user_insert(&$edit, $account, $category) {
  if (in_array(MODELPLATFORM_MODEL_ROLE_NAME, $account->roles)) {
    $node = new stdClass();

    $node->title = $account->name;
    $node->type = 'node_gallery_gallery';
    $node->uid = $account->uid;

    node_save($node);

    $new_revision = (object) array(
      'from_state' => workbench_moderation_state_none(),
      'state' => workbench_moderation_state_published(),
      'nid' => $node->nid,
      'vid' => $node->vid,
      'uid' => $account->uid,
      'is_current' => TRUE,
      'published' => TRUE,
      'stamp' => $node->changed,
    );
    $node->workbench_moderation = array();
    $node->workbench_moderation['my_revision'] = $new_revision;
    $node->workbench_moderation['current'] = $new_revision;

    node_save($node);
  }
}