<?php

/**
 * @file
 * Model Platform - Galleries module.
 */

/**
 * Implements hook_module_implements_alter().
 */
function mp_galleries_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'user_insert') {
    $group = $implementations['mp_galleries'];
    unset($implementations['mp_galleries']);
    $implementations['mp_galleries'] = $group;
  }
}

/**
 * Implements hook_user_insert().
 */
function mp_galleries_user_insert(&$edit, $account, $category) {
  if (in_array(MODELPLATFORM_MODEL_ROLE_NAME, $account->roles)) {
    $node = new stdClass();

    $node->title = $account->name;
    $node->type = 'node_gallery_gallery';
    $node->uid = $account->uid;

    node_save($node);

    $from_state = workbench_moderation_state_none();
    $state = workbench_moderation_state_published();
    $new_revision = _mp_galleries_create_revision($node, $from_state, $state);

    $node->workbench_moderation = array();
    $node->workbench_moderation['my_revision'] = $new_revision;
    $node->workbench_moderation['current'] = $new_revision;

    node_save($node);
  }
}

/**
 * Implements hook_node_insert().
 */
function mp_galleries_node_insert($node) {
  if ($node->type === 'node_gallery_item') {
    $from_state = workbench_moderation_state_none();
    $state = 'needs_review';
    $new_revision = _mp_galleries_create_revision($node, $from_state, $state);

    $node->workbench_moderation_state_new = $state;
    $node->workbench_moderation['my_revision'] = $new_revision;
    $node->workbench_moderation['current'] = $new_revision;
  }
}

/**
 * Implements hook_node_presave().
 */
function mp_galleries_node_presave($node) {
  if ($node->type === 'node_gallery_item') {
    $field_main_picture = field_get_items('node', $node, 'field_main_picture');
    if (isset($field_main_picture[0]['value']) && $field_main_picture[0]['value'] == TRUE) {
      // Assign picture to the user if approved.
      // 91 - approved.
      if (isset($node->field_ver_status[LANGUAGE_NONE][0]['tid'])
        && $node->field_ver_status[LANGUAGE_NONE][0]['tid'] == 91
      ) {
        $nids = db_select('node', 'n')
          ->condition('n.type', 'node_gallery_item')
          ->condition('n.uid', $node->uid)
          ->condition('n.nid', $node->nid, '!=')
          ->fields('n', array('nid'))
          ->execute()
          ->fetchCol(0);

        db_update('field_data_field_main_picture')
          ->condition('entity_id', $nids, 'IN')
          ->condition('entity_type', 'node')
          ->fields(array(
            'field_main_picture_value' => 0,
          ))
          ->execute();

        if (isset($node->node_gallery_media[LANGUAGE_NONE][0]['fid'])) {
          $account = user_load($node->uid);
          $picture = file_load($node->node_gallery_media[LANGUAGE_NONE][0]['fid']);
          $account->picture = $picture;
          user_save($account);
        }
      }
    }
  }
}

/**
 * Create new revision.
 */
function _mp_galleries_create_revision($node, $from_state, $state) {
  $new_revision = (object) array(
    'from_state' => $from_state,
    'state' => $state,
    'nid' => $node->nid,
    'vid' => $node->vid,
    'uid' => $node->uid,
    'is_current' => TRUE,
    'published' => TRUE,
    'stamp' => $node->changed,
  );

  return $new_revision;
}