<?php 
	
	function model_block_info() {    
	  $blocks['model_video'] = array(
	    // info: The name of the block.
	    'info' => t('Model videos to show'),
	  );

	  return $blocks;
	}

	function model_block_view($delta = '') {
	  $uid = arg(2);
	  $block['subject'] = t('');
	  $profile = db_select('profile', 'p')
	    ->fields('p')
	    ->condition('uid', $uid, '=')
	    ->condition('type','model_videos', '=')
	    ->execute()
	    ->fetchAssoc();

	  $videos = db_select('field_data_field_videos', 'video')
	    ->fields('video')
	    ->condition('entity_id', $profile['pid'],'=')
	    ->execute();

	    $block['content'] = '<div class="book-videos">';
	    foreach($videos as $video) {
	    	$url = $video->field_videos_video_url;
	    	$url=explode('?v=', $url);
	      $block['content'].= '<iframe style="margin:10px; width="300" height="280"src="https://www.youtube.com/embed/'.$url[1].'"></iframe>';
	    }
	    $block['content'] .="</div>";
	return $block;
	}

	/**
	 * Implements hook_menu().
	 */
	function model_menu() {
	  $items = array();

	  $items['user/%user/hybridauth'] = array(
	    'title' => '',
	    'page callback' => 'hybridauth_user_identity',
	    'page arguments' => array(1),
	    'access callback' => 'user_edit_access',
	    'access arguments' => array(1),
	    'file' => 'hybridauth.pages.inc',
	    'type' => MENU_LOCAL_TASK,
	  );
	  return $items;
	}
?>