<?php

require_once 'mp_forms.inc';

/**
 * Implements hook_form_profile2_form_alter().
 */
function mp_forms_form_profile2_form_alter(&$form, &$form_state) {
  if (isset($form['#user_category'])) {
    $profile_id = 'profile_' . $form['#user_category'];

    switch ($form['#user_category']) {
      case 'model_private_data':
        _mp_forms_model_private_data_form($form, $form_state, $profile_id);
        break;

      case 'model_basic_informaiton':
        _mp_forms_model_basic_informaiton_form($form, $form_state, $profile_id);
        break;

      default:
        // Nothing to do.
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function mp_forms_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form':
      $selector = 'input[name="user_roles"]';
      $form['field_small_business']['#states'] = array(
        'visible' => array(
          array(
            $selector => array(
              'value' => 5,
            ),
          ),
        ),
        'invisible' => array(
          array(
            $selector => array(
              '!value' => 5,
            ),
          ),
        ),
      );

      $form['autoassignrole_user']['#weight'] = -100;
      $form['#attached']['js'] = array(
        array(
          'data' => array(
            'mp_forms' => array(
              'model' => 5,
              'customer' => 4,
            ),
          ),
          'type' => 'setting',
        ),
        array(
          'data' => drupal_get_path('module', 'mp_forms') . '/js/mp_forms.js',
        ),
      );
      break;

    default:
      // Nothing to do.
  }
}
