<?php

require_once 'modelplatform.inc';

// Roles.
define('MODELPLATFORM_MODEL_ROLE_NAME', 'Model');

// Vocabularies.
define('MODELPLATFORM_VOCABULARY_AGE_CATEGORY', 'age_category');

/**
 * Implements hook_form_alter().
 */
function modelplatform_form_alter(&$form, &$form_state, $form_id) {
  switch($form_id) {
    case 'user_profile_form':
      if (isset($form['field_model_is_active'])) {
        $access = in_array(MODELPLATFORM_MODEL_ROLE_NAME, $form['#user']->roles);
        $access = $access && user_access('modelplatform administer models');
        $form['field_model_is_active']['#access'] = $access;
      }
      break;

    case 'user_pass_reset':
      if (isset($form['message']['#markup'])) {
        drupal_set_title(t('One-time login'));
        $message = t('<p>Click on this button to log in to the site.</p>');
        $form['message']['#markup'] = $message;
      }
      break;

    default:
      // Nothing to do.
  }
}

/**
 * Implements hook_permission().
 */
function modelplatform_permission() {
  $permissions = array(
    'modelplatform administer models' => array(
      'title' => t('Administer models'),
      'description' => t('Can moderate models profiles.'),
    ),
  );

  return $permissions;
}