<?php

/**
 * @file
 * Model Platform Email Module.
 */

require_once 'mp_emails.inc';
require_once 'mp_emails.emails.inc';

/**
 * Implements hook_mpb_option_model().
 */
function mp_emails_mpb_option_model($event) {
  $email_params = _mp_emails_get_event_params($event);
  _mp_emails_model_job_option_notification($email_params);
  _mp_emails_customer_job_option_notification($email_params);
}

/**
 * Implements hook_mpb_option_model_accept().
 */
function mp_emails_mpb_option_model_accept($auction) {
  $auction_wrapper = entity_metadata_wrapper('mp_auction', $auction);
  $decision_user = $auction_wrapper->field_decision_user->value();
  $event = $auction_wrapper->field_auction_event->value();
  $email_params = _mp_emails_get_event_params($event);
  if (_modelplatform_user_is_model($decision_user)) {
    _mp_emails_customer_job_option_model_confirm($email_params);
  }
  else {
    _mp_emails_model_job_confirmed($email_params);
  }
}

/**
 * Implements hook_mpb_option_model_decline().
 */
function mp_emails_mpb_option_model_decline($auction) {
  $auction_wrapper = entity_metadata_wrapper('mp_auction', $auction);
  $decision_user = $auction_wrapper->field_decision_user->value();
  $event = $auction_wrapper->field_auction_event->value();
  $email_params = _mp_emails_get_event_params($event);
  if (_modelplatform_user_is_model($decision_user)) {
    _mp_emails_customer_job_option_model_confirm($email_params);
  }
  else {
    _mp_emails_model_job_confirmed($email_params);
  }
}

/**
 * Implements hook_mail().
 */
function mp_emails_mail($key, &$message, $params) {
  switch($key) {
    case 'mp_emeils_job_propose':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;

    default:
      // Nothing to do.
  }
}